version: '3.8'

services:
  db:
    image: supabase/postgres:14.1.0.55
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=rPwYLhsOg8LpbsUs
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - AWS_ACCESS_KEY_ID=<your-aws-access-key>
      - AWS_SECRET_ACCESS_KEY=<your-aws-secret-access-key>
      - AWS_REGION=eu-central-1
      - AWS_S3_BUCKETS=aprozar
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - db
    restart: unless-stopped

  app:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres?sslmode=require
      - DB_USERNAME=postgres
      - DB_PASSWORD=rPwYLhsOg8LpbsUs
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  web:
    build: ./frontend
    ports:
      - 3000:3000
networks:
  db:
    driver: bridge

